In [143]:
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz

--2026-05-12 18:19:55--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz [following]
--2026-05-12 18:19:56--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7725286 (7.4M) [application/octet-stream]
Saving to: ‘SQuAD_it-train.json.gz.1’

SQuAD_it-train.json 100%[===================>]   7.37M  23.4MB/s    in 0.3s

2026-05-12 18:19:57 (23.4 MB/s) - ‘SQuAD_it-train.json.gz.1’ saved [7725286/7725286]

--2026-05-12 18:19:57--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz [following]
--2026-05-12 18:19:58--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1051245 (1.0M) [application/octet-stream]
Saving to: ‘SQuAD_it-test.json.gz.1’

SQuAD_it-test.json. 100%[===================>]   1.00M  --.-KB/s    in 0.09s

2026-05-12 18:19:58 (11.3 MB/s) - ‘SQuAD_it-test.json.gz.1’ saved [1051245/1051245]

In [144]:
from datasets import load_dataset

squard_it_dataset = load_dataset("json", data_files="SQuAD_it-train.json.gz", field="data")

In [145]:
squard_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
})

In [146]:
squard_it_dataset["train"][0]

{'title': 'Terremoto del Sichuan del 2008',
 'paragraphs': [{'context': "Il terremoto del Sichuan del 2008 o il terremoto del Gran Sichuan, misurato a 8.0 Ms e 7.9 Mw, e si è verificato alle 02:28:01 PM China Standard Time all' epicentro (06:28:01 UTC) il 12 maggio nella provincia del Sichuan, ha ucciso 69.197 persone e lasciato 18.222 dispersi.",
   'qas': [{'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56cdca7862d2951400fa6826',
     'question': 'In quale anno si è verificato il terremoto nel Sichuan?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56cdca7862d2951400fa6828',
     'question': 'Quante persone sono state uccise come risultato?'},
    {'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56d4f9902ccc5a1400d833c0',
     'question': 'Quale anno ha avuto luogo il terremoto del Sichuan?'},
    {'answers': [{'answer_start': 78, 'text': '8.0 Ms e 7.9 Mw'}],
     'id': '56d4f9902ccc5a1400d833c1',
     'question': 'Che cosa ha fatto la misura di sisma?'},
    {'answers': [{'answer_start': 183, 'text': '12 maggio'}],
     'id': '56d4f9902ccc5a1400d833c2',
     'question': 'Che giorno si è verificato il terremoto?'},
    {'answers': [{'answer_start': 118,
       'text': '02:28:01 PM China Standard Time'}],
     'id': '56d4f9902ccc5a1400d833c3',
     'question': 'Che ora del giorno è accaduto il terremoto?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56d4f9902ccc5a1400d833c4',
     'question': 'Quante persone sono morte?'}]},
  {'context': 'E\' noto anche come terremoto di Wenchuan (Cinese:????; pinyin: Wènchu? n dà dìzhèn; letteralmente:"Grande terremoto di Wenchuan"), dopo l\' ubicazione dell\' epicentro del terremoto, Wenchuan County, Sichuan. L\' epicentro era di 80 chilometri (50 miglia) ad ovest nord-ovest di Chengdu, capoluogo di provincia, con una profondità focale di 19 km (12 miglia). Il terremoto ha colpito anche i paesi vicini e lontani da Pechino e Shanghai-1.500 km (930 mi) e 1.700 km (1.060 mi) di distanza, dove gli edifici adibiti a uffici hanno oscillato con il tremore. Forti scosse di assestamento, un po\' superiori alla magnitudo 6, hanno continuato a colpire l\' area anche mesi dopo il sisma principale, causando nuove vittime e danni.',
   'qas': [{'answers': [{'answer_start': 415, 'text': 'Pechino e Shanghai'}],
     'id': '56cdcb2c62d2951400fa6830',
     'question': 'Quali città lontane in altri paesi potrebbero sentire il terremoto?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56cdcb2c62d2951400fa6833',
     'question': 'Qual è stata la profondità focale del terremoto?'},
    {'answers': [{'answer_start': 659, 'text': 'mesi dopo'}],
     'id': '56cdcb2c62d2951400fa6834',
     'question': 'Quanto tempo dopo il terremoto si sono sentite le scosse di assestamento?'},
    {'answers': [{'answer_start': 181, 'text': 'Wenchuan County, Sichuan'}],
     'id': '56d4fb6f2ccc5a1400d833d5',
     'question': "Dov' era l' epicentro del terremoto?"},
    {'answers': [{'answer_start': 227, 'text': '80 chilometri'}],
     'id': '56d4fb6f2ccc5a1400d833d6',
     'question': 'Quanto lontano era da Chengdu?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56d4fb6f2ccc5a1400d833d7',
     'question': 'Qual era la profondità focale del sisma?'}]},
  {'context': "I dati ufficiali (al 21 luglio 2008 ore 12:00 CST) hanno dichiarato che 69.197 sono stati confermati morti, di cui 68.636 nella provincia del Sichuan e 374.176 feriti, di cui 18.222 scomparsi. Il terremoto ha lasciato circa 4,8 milioni di senzatetto, anche se il numero potrebbe raggiungere gli 11 milioni. Circa 15 milioni di persone vivevano nell' area colpita. E' stato il terremoto più mortale per colpire la Cina dopo il terremoto di Tangshan 1976, che ha ucciso almeno 240.000 persone, e il più forte del paese dal terremoto di Chayu 1950, che ha registrato a 8,5 sulla scala di magnitudo Richter. E' il 21° terremoto più morto di tutti i tempi. Il 6 novembre 2008, il governo centrale ha annunciato che avrebbe speso 1 trilione di RMB (circa 146,5 miliardi di dollari USA) nei prossimi tre anni per ricostruire le aree devastate dal terremoto, come parte del programma cinese di stimolo economico.",
   'qas': [{'answers': [{'answer_start': 72, 'text': '69.197'}],
     'id': '56cdcbb762d2951400fa683a',
     'question': 'Quante persone sono state confermate morte?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56cdcbb762d2951400fa683b',
     'question': 'Quanti morti sono stati confermati solo nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56cdcbb762d2951400fa683c',
     'question': 'Quante persone sono rimaste senza tetto a causa del terremoto?'},
    {'answers': [{'answer_start': 313, 'text': '15 milioni'}],
     'id': '56cdcbb762d2951400fa683d',
     'question': 'Quante persone hanno vissuto nella zona colpita?'},
    {'answers': [{'answer_start': 724, 'text': '1 trilione di RMB'}],
     'id': '56cdcbb762d2951400fa683e',
     'question': 'Quanto denaro è stato destinato alla ricostruzione di aree devastate?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56d4fca52ccc5a1400d833de',
     'question': 'Quante persone sono morte nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 152, 'text': '374.176'}],
     'id': '56d4fca52ccc5a1400d833df',
     'question': 'Quanti sono stati feriti nel Sichuan?'},
    {'answers': [{'answer_start': 175, 'text': '18.222'}],
     'id': '56d4fca52ccc5a1400d833e0',
     'question': 'Quante persone sono elencate come scomparse?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56d4fca52ccc5a1400d833e1',
     'question': 'Quante persone sono senzatetto a causa del terremoto?'},
    {'answers': [{'answer_start': 295, 'text': '11 milioni'}],
     'id': '56d4fca52ccc5a1400d833e2',
     'question': 'Quanto potrebbe arrivare il numero dei senzatetto?'}]},
  {'context': "Il terremoto ha avuto una magnitudine di 8,0 Ms e 7,9 Mw. L' epicentro è stato in Wenchuan County, Ngawa Tibetano e Prefettura Autonoma di Qiang, 80 km ad ovest / nord-ovest del capoluogo di provincia di Chengdu, con il suo tremore principale che si verifica alle 14:28:01.42 China Standard Time (06:28:01.42 UTC), il 12 maggio 2008 della durata di circa 2 minuti, nel terremoto quasi l' 80% degli edifici sono stati distrutti.",
   'qas': [{'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56cdcc5562d2951400fa6847',
     'question': 'Quanto tempo è durato il terremoto?'},
    {'answers': [{'answer_start': 388, 'text': '80%'}],
     'id': '56cdcc5562d2951400fa6848',
     'question': 'Quale percentuale di edifici è stata distrutta?'},
    {'answers': [{'answer_start': 41, 'text': '8,0 Ms e 7,9 Mw'}],
     'id': '56d4fe332ccc5a1400d833e8',
     'question': 'Qual era la magnitudo del terremoto?'},
    {'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56d4fe332ccc5a1400d833eb',
     'question': 'Quanto tempo è durato il tremore principale?'},
    {'answers': [{'answer_start': 379, 'text': "quasi l' 80%"}],
     'id': '56d4fe332ccc5a1400d833ec',
     'question': 'Quale percentuale di edifici è stata distrutta durante il sisma?'}]},
  {'context': "Secondo uno studio della China Earthquake Administration (CEA), il terremoto si è verificato lungo la faglia Longmenshan, una struttura di spinta lungo il confine della piastra Indo-Australiana e placca eurasiatica. Le attività sismiche si sono concentrate sulla sua frattura media (nota come frattura Yingxiu-Beichuan). La rottura è durata quasi 120 sec, con la maggior parte dell' energia rilasciata nei primi 80 sec. Partendo da Wenchuan, la rottura si propagò ad una velocità media di 3,1 chilometri al secondo 49° verso nord-est, rompendosi per un totale di circa 300 km. Lo spostamento massimo ammontava a 9 metri. Il fuoco era più profondo di 10 km.",
   'qas': [{'answers': [{'answer_start': 347, 'text': '120 sec'}],
     'id': '56cdccd962d2951400fa6850',
     'question': 'Quanto tempo ha durato la rottura?'},
    {'answers': [{'answer_start': 650, 'text': '10 km'}],
     'id': '56cdccd962d2951400fa6852',
     'question': 'Quanto è stato profondo il centro del terremoto?'},
    {'answers': [{'answer_start': 293, 'text': 'frattura Yingxiu-Beichuan'}],
     'id': '56d5005d2ccc5a1400d833f4',
     'question': 'Su quale frattura ha messo a fuoco il terremoto?'},
    {'answers': [{'answer_start': 612, 'text': '9 metri'}],
     'id': '56d5005d2ccc5a1400d833f6',
     'question': 'Qual è stato lo sfollamento più causato dal terremoto?'}]},
  {'context': 'Yazhou Zhoukan, con sede in Malesia, ha condotto un\' intervista con l\' ex ricercatore presso il China Seismological Bureau Geng Qingguo (??), in cui Geng ha sostenuto che un rapporto scritto riservato è stato inviato all\' Ufficio sismologico di Stato il 30 aprile 2008, avvertendo circa il possibile verificarsi di un terremoto significativo nella regione della prefettura di Ngawa del Sichuan intorno all\' 8 maggio, con una gamma di 10 giorni prima o dopo il terremoto. Il Geng, pur riconoscendo che la predizione del terremoto era ampiamente considerata problematica dalla comunità scientifica, credeva che "più grande è il terremoto, più facile è prevedere". Geng aveva a lungo tentato di stabilire una correlazione tra il verificarsi di siccità e terremoti; Premier Zhou Enlai ha riferito che ha preso interesse nel lavoro di Geng. La teoria di correlazione siccità-terra terremoto di Geng è stata pubblicata per la prima volta nel 1972, e ha detto di aver pronosticato con successo i terremoti di Haicheng 1975 e 1976 Tangshan. Lo stesso articolo di Yazhou Zhoukan ha sottolineato le difficoltà intrinseche associate alla previsione dei terremoti.',
   'qas': [{'answers': [{'answer_start': 936, 'text': '1972'}],
     'id': '56cdce0b62d2951400fa685b',
     'question': 'Quando è stata rilasciata la teoria di correlazione siccità-terra terremoto di Geng?'},
    {'answers': [{'answer_start': 394, 'text': "intorno all' 8 maggio"}],
     'id': '56d67a8d1c8504140094714f',
     'question': 'Qual era il tempo previsto per il terremoto?'},
    {'answers': [{'answer_start': 741, 'text': 'siccità'}],
     'id': '56d67a8d1c85041400947150',
     'question': 'Che cosa ha cercato Geng a lungo di stabilire come rapporto con i terremoti?'}]},
  {'context': 'In uno studio dell\' USGS (United States Geological Survey) i modelli preliminari di rottura del terremoto hanno indicato uno spostamento fino a 9 metri lungo un guasto lungo circa 240 km di lunghezza e 20 km di profondità. Il terremoto ha generato deformazioni della superficie superiori a 3 metri e ha aumentato lo stress (e la probabilità che si verifichino eventi futuri) alle estremità nord-orientale e sud-occidentale del guasto. Il 20 maggio, il sismologo dell\' USGS Tom Parsons ha avvertito che c\' è "alto rischio" di una grave scossa di assestamento M>7 nelle prossime settimane o mesi.',
   'qas': [{'answers': [{'answer_start': 137, 'text': 'fino a 9 metri'}],
     'id': '56cdcebe62d2951400fa6862',
     'question': 'Quanto è stato grande lo spostamento?'},
    {'answers': [{'answer_start': 473, 'text': 'Tom Parsons'}],
     'id': '56cdcebe62d2951400fa6866',
     'question': "Chi ha prima messo in guardia da possibili attività sismiche nell' area?"},
    {'answers': [{'answer_start': 144, 'text': '9 metri'}],
     'id': '56d5027a9d1b871400ae05e1',
     'question': "Che cosa ha mostrato il Geological Survey degli Stati Uniti come l' entità dello spostamento?"},
    {'answers': [{'answer_start': 202, 'text': '20 km di profondità'}],
     'id': '56d5027a9d1b871400ae05e3',
     'question': 'Quanto è profondo il guasto?'},
    {'answers': [{'answer_start': 508, 'text': 'alto rischio'}],
     'id': '56d5027a9d1b871400ae05e5',
     'question': 'Che cosa ha considerato Tom Parsons come il fattore di rischio per forti terremoti futuri?'}]},
  {'context': 'Sismologo giapponese Yuji Yagi Yuji Yagi presso l\' Università di Tsukuba ha detto che il terremoto si è verificato in due fasi:"Il 155 miglia Longmenshan Fault tore in due sezioni, il primo uno strappo di circa sette metri, seguita da un secondo che ha tosato quattro metri". I suoi dati hanno anche mostrato che il terremoto è durato circa due minuti e ha rilasciato 30 volte l\' energia del grande terremoto di Hanshin del 1995 in Giappone, che ha ucciso oltre 6.000 persone. Egli ha sottolineato che la scarsità dell\' epicentro e la densità di popolazione hanno notevolmente aumentato la gravità del terremoto. Teruyuki Kato, un sismologo dell\' Università di Tokyo, ha detto che le onde sismiche del terremoto hanno percorso una lunga distanza senza perdere il loro potere a causa della fermezza del terreno nella Cina centrale.',
   'qas': [{'answers': [{'answer_start': 115, 'text': 'in due fasi'}],
     'id': '56d504539d1b871400ae05eb',
     'question': 'Come ha fatto Yuji Yagi a dire che il terremoto è successo?'},
    {'answers': [{'answer_start': 142, 'text': 'Longmenshan Fault'}],
     'id': '56d504539d1b871400ae05ec',
     'question': 'Che errore si è verificato in due luoghi?'},
    {'answers': [{'answer_start': 368, 'text': '30 volte'}],
     'id': '56d504539d1b871400ae05ee',
     'question': 'Quanta più energia di quella prodotta dal terremoto del 1995 in Giappone?'},
    {'answers': [{'answer_start': 789, 'text': 'fermezza del terreno'}],
     'id': '56d504539d1b871400ae05ef',
     'question': 'Perché le onde sismiche hanno viaggiato finora?'}]},
  {'context': 'Tra 64 e 104 scosse di assestamento importanti, di magnitudo compresa tra 4,0 e 6,1, sono state registrate entro 72 ore dal sisma principale. Secondo i conteggi ufficiali cinesi,"alle ore 12:00 CST, 6 novembre 2008 c\' erano state 42.719 scariche post-shock totali, di cui 246 variavano da 4,0 SM a 4,9 SM, 34 da 5,0 MS a 5,9 MS, e 8 da 6,0 Ms a 6,4 MS; l\' urto post-shock più forte misurato 6,4 MS." L\' ultima scossa post-shock superiore a M6 si è verificato il 5 agosto.',
   'qas': [{'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56cdd08862d2951400fa6894',
     'question': 'Quante sono state le scosse di assestamento?'},
    {'answers': [{'answer_start': 107,
       'text': 'entro 72 ore dal sisma principale'}],
     'id': '56cdd08862d2951400fa6896',
     'question': 'Quando sono state registrate le scosse di assestamento?'},
    {'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56d505f99d1b871400ae05f5',
     'question': 'Quante sono state le scosse di assestamento entro 72 ore?'},
    {'answers': [{'answer_start': 230, 'text': '42.719'}],
     'id': '56d505f99d1b871400ae05f6',
     'question': 'Che cosa dicono i cinesi è il numero totale di shock dopo il terremoto?'},
    {'answers': [{'answer_start': 272, 'text': '246'}],
     'id': '56d505f99d1b871400ae05f8',
     'question': 'In quale data si sono verificate le scosse di assestamento più recenti superiori a 6 SM?'}]},
  {'context': '(Il terremoto della sig. ra 6.1 del 30 agosto 2008 nel Sichuan meridionale non faceva parte di questa serie perché è stato causato da una diversa colpa.',
   'qas': [{'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a0',
     'question': 'Dove si è verificato il terremoto?'},
    {'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a2',
     'question': "Dov' era il terremoto del 30 agosto 2008?"},
    {'answers': [{'answer_start': 20, 'text': 'sig'}],
     'id': '56d507269d1b871400ae05ff',
     'question': 'Qual era la grandezza del terremoto del Sichuan meridionale?'}]},
  {'context': 'La mappa dell\' intensità sismica pubblicata dal CEA dopo aver rilevato 500.000 km2 dell\' area colpita mostra una liedu massima di XI sulla scala di intensità sismica cinese (CSIS), descritta come "molto distruttiva" sulla scala macrosismica europea (EMS) da cui il CSIS ha tratto riferimento. (USGS, utilizzando la scala di intensità Mercalli modificata (CC), collocava anche l\' intensità massima a XI,"molto disastrosa". Due strisce sud-ovest-nord-est di liedu XI sono centrate intorno a Yingxiu, Wenchuan (la città più vicina all\' epicentro del terremoto principale) e Beichuan (la città ripetutamente colpita da forti scosse di assestamento tra cui una che registra MS 6.1 il 1 agosto 2008), entrambe nella provincia del Sichuan, occupando un totale di 2.419 km2. La zona Yingxiu liedu-XI è lunga circa 66 km e larga 20 km lungo Wenchuan-Dujiangyan-Pengzhou; la zona Beichuan liedu-XI è lunga circa 82 km e larga 15 km lungo An County-Beichuan-Pingwu. L\' area con liedu X (comparabile a X su EMS,"distruttivo" e X su MM,"disastroso") ha una superficie di 3.144 km2.',
   'qas': [{'answers': [{'answer_start': 48, 'text': 'CEA'}],
     'id': '56cdd21562d2951400fa68b0',
     'question': "Chi ha pubblicato la mappa dell' intensità dei terremoti?"},
    {'answers': [{'answer_start': 130, 'text': 'XI'}],
     'id': '56cdd21562d2951400fa68b2',
     'question': 'A quale intensità è stata scalata?'},
    {'answers': [{'answer_start': 489, 'text': 'Yingxiu, Wenchuan'}],
     'id': '56d5098a9d1b871400ae0609',
     'question': "Quale città era più vicina all' epicentro principale?"}]},
  {'context': "Il sistema Longmen Shan Fault System si trova al confine orientale dell' altopiano tibetano e contiene diversi difetti. Questo terremoto ha rotto almeno due strutture imbricate in Longmen Shan Fault System, vale a dire il Fault Beichuan e il Guanxian-Anxian Fault. Nell' area epicentrale, lo slittamento medio in Fault Beichuan era di circa 3,5 metri (11 ft) verticale, di 3,5 metri (11 ft) orizzontale parallelo al guasto, e di 4,8 metri (16 ft) orizzontale-pendicolare al guasto. Nell' area di circa 30 chilometri (19 miglia) a nord-est dell' epicentro, lo scivolamento superficiale su Beichuan Fault è stato quasi esclusivamente dextral strike-slip fino a circa 3 metri, mentre lo scivolamento medio in Guanxian-Anxian Fault è stato di circa 2 metri verticali (6 ft 7 in) e 2,3 metri (7 ft 7 in) orizzontali. il confine orientale dell' altopiano tibetano.",
   'qas': [{'answers': [{'answer_start': 665, 'text': '3 metri'}],
     'id': '56cdd4d762d2951400fa68cd',
     'question': 'Quanto è stato grande lo slip 30 km a nord-est del guasto?'},
    {'answers': [{'answer_start': 745, 'text': '2 metri'}],
     'id': '56cdd4d762d2951400fa68ce',
     'question': 'Qual è stato lo slittamento verticale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 777, 'text': '2,3 metri'}],
     'id': '56cdd4d762d2951400fa68cf',
     'question': 'Che cosa è stato lo slittamento orizzontale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 73, 'text': 'altopiano tibetano'}],
     'id': '56cdd4d762d2951400fa68d0',
     'question': 'Dove si trova il guasto dello shan Longmen?'},
    {'answers': [{'answer_start': 3,
       'text': 'sistema Longmen Shan Fault System'}],
     'id': '56d516439d1b871400ae0611',
     'question': 'Dove sono i guasti Beichuan e Guanxian-Ansia?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0612',
     'question': 'Qual è stato lo slittamento verticale medio nel difetto di Beichaun?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0613',
     'question': "Qual è stato lo slittamento orizzontale nel Fault Beichuan all' epicentro?"},
    {'answers': [{'answer_start': 429, 'text': '4,8 metri'}],
     'id': '56d516439d1b871400ae0614',
     'question': 'Qual è stato lo slittamento orizzontale perpendicolare al guasto?'}]},

In [147]:
data_files = {"train": "SQuAD_it-train.json.gz", "test": "SQuAD_it-test.json.gz"}
squard_it_dataset = load_dataset("json", data_files=data_files, field="data")

In [148]:
squard_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

In [149]:
url = "https://github.com/crux82/squad-it/raw/master/"
data_files = {
    "train": url + "SQuAD_it-train.json.gz",
    "test": url + "SQuAD_it-test.json.gz",
}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")

In [150]:
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip"
!unzip drugsCom_raw.zip

--2026-05-12 18:20:01--  https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘drugsCom_raw.zip.1’

drugsCom_raw.zip.1      [<=>                 ]       0  --.-KB/s               ^C
Archive:  drugsCom_raw.zip
replace drugsComTest_raw.tsv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C

In [154]:
from datasets import load_dataset

data_files = {"train": "drugsComTrain_raw.tsv", "test": "drugsComTest_raw.tsv"}
drug_dataset = load_dataset("csv", data_files=data_files, delimiter="\t")

In [155]:
drug_dataset = drug_dataset["train"].shuffle(seed=42).select(range(1000))
drug_dataset[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

In [156]:
for split in drug_dataset.keys():
    assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

AttributeError: 'Dataset' object has no attribute 'keys'

In [157]:
print(type(drug_dataset))
print(drug_dataset)

<class 'datasets.arrow_dataset.Dataset'>
Dataset({
    features: ['Unnamed: 0', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
    num_rows: 1000
})

In [158]:
assert len(drug_dataset) == len(drug_dataset.unique("Unnamed: 0"))

In [159]:
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0", new_column_name="patient_id"
)
drug_dataset

Dataset({
    features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
    num_rows: 1000
})

In [160]:
def lowercase_review(example):
    return {"condition": example["condition"].lower()}

drug_dataset.map(lowercase_review)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

AttributeError: 'NoneType' object has no attribute 'lower'

In [161]:
def filter_nones(x):
    return x["condition"] is not None

In [162]:
(lambda x: x*x)(3)

9

In [163]:
(lambda base, weight: 0.5 * base * weight)(4, 8)

16.0

In [164]:
drug_dataset = drug_dataset.filter(lambda x: x["condition"] is not None)

In [165]:
drug_dataset = drug_dataset.map(lowercase_review)
drug_dataset["condition"][:3]

['gout, acute', 'ibromyalgia', 'inflammatory conditions']

In [166]:
def compute_review_length(example):
    return {"review_length": len(example["review"].split())}

In [167]:
drug_dataset = drug_dataset.map(compute_review_length)
drug_dataset[0]

Map:   0%|          | 0/991 [00:00<?, ? examples/s]

{'patient_id': 87571,
 'drugName': 'Naproxen',
 'condition': 'gout, acute',
 'review': '"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
 'rating': 9.0,
 'date': 'September 2, 2015',
 'usefulCount': 36,
 'review_length': 32}

In [168]:
drug_dataset.sort("review_length")[:3]

{'patient_id': [28453, 150835, 95509],
 'drugName': ['Lexapro',
  'Sulfamethoxazole / trimethoprim',
  'Acetaminophen / diphenhydramine'],
 'condition': ['anxiety', 'bronchitis', 'insomnia'],
 'review': ['"(escitalopram)"', '"Great!"', '"Great"'],
 'rating': [9.0, 8.0, 8.0],
 'date': ['July 17, 2013', 'October 18, 2013', 'May 11, 2017'],
 'usefulCount': [16, 3, 3],
 'review_length': [1, 1, 1]}

In [169]:
drug_dataset = drug_dataset.filter(lambda x: x["review_length"] > 30)

Filter:   0%|          | 0/991 [00:00<?, ? examples/s]

In [170]:
print(drug_dataset.num_rows)

866

In [171]:
import html

text = "I&#039;m a transformer called BERT"
html.unescape(text)

"I'm a transformer called BERT"

In [172]:
drug_dataset = drug_dataset.map(lambda x: {"review": html.unescape(x["review"])})

Map:   0%|          | 0/866 [00:00<?, ? examples/s]

In [173]:
new_drug_dataset = drug_dataset.map(
    lambda x: {"review": [html.unescape(o) for o in x["review"]]}, batched=True
)

Map:   0%|          | 0/866 [00:00<?, ? examples/s]

In [174]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")


def tokenize_function(examples):
    return tokenizer(examples["review"], truncation=True)

In [175]:
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/866 [00:00<?, ? examples/s]

CPU times: user 145 ms, sys: 28.1 ms, total: 174 ms
Wall time: 228 ms

In [176]:
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=False)

Map:   0%|          | 0/866 [00:00<?, ? examples/s]

CPU times: user 172 ms, sys: 9.47 ms, total: 181 ms
Wall time: 185 ms

In [177]:
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)

def slow_tokenize_function(examples):
    return slow_tokenizer(examples["review"], truncation=True)

tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=8)

Map (num_proc=8):   0%|          | 0/866 [00:00<?, ? examples/s]

In [178]:
def tokenize_and_split(examples):
    return tokenizer(
        examples["review"],
        truncation=True,
        max_length=512,
        return_overflowing_tokens=True,
    )

In [179]:
result = tokenize_and_split(drug_dataset[0])
[len(inp) for inp in result["input_ids"]]

[55]

In [180]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)

Map:   0%|          | 0/866 [00:00<?, ? examples/s]

In [181]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True, remove_columns=drug_dataset.column_names)

Map:   0%|          | 0/866 [00:00<?, ? examples/s]

In [182]:
len(tokenized_dataset)

866

In [183]:
def tokenize_and_split(examples):
    result = tokenizer(examples["review"],
                       truncation=True,
                       max_length=128,
                       return_overflowing_tokens=True)
    
    sample_map = result.pop("overflow_to_sample_mapping")
    for key, values in examples.items():
        result[key] = [values[i] for i in sample_map]
    return result

In [184]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)

Map:   0%|          | 0/866 [00:00<?, ? examples/s]

In [185]:
tokenized_dataset

Dataset({
    features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 1286
})

In [186]:
drug_dataset.set_format("pandas")

In [187]:
drug_dataset[:3]

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,87571,Naproxen,"gout, acute","""like the previous person mention, I'm a stron...",9.0,"September 2, 2015",36,32
1,178045,Duloxetine,ibromyalgia,"""I have taken Cymbalta for about a year and a ...",3.0,"November 7, 2011",13,100
2,80482,Mobic,inflammatory conditions,"""I have been taking Mobic for over a year with...",10.0,"June 5, 2013",128,46

In [188]:
train_df = drug_dataset[:]

In [189]:
frequencies = (
    train_df["condition"]
    .value_counts()
    .to_frame()
    .reset_index()
    .rename(columns={"index": "condition", "count": "frequency"})
)
frequencies.head()

       condition  frequency
0  birth control        144
1     depression         56
2        anxiety         29
3           acne         26
4       insomnia         26

In [190]:
from datasets import Dataset
freq_dataset = Dataset.from_pandas(frequencies)
freq_dataset

Dataset({
    features: ['condition', 'frequency'],
    num_rows: 157
})

In [191]:
drug_dataset.reset_format()

In [192]:
temp = drug_dataset.train_test_split(train_size=0.8, seed=42)

drug_dataset_clean = temp
drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")

split2 = drug_dataset_clean["train"].train_test_split(train_size=0.875, seed=42)
drug_dataset_clean["train"] = split2["train"]
drug_dataset_clean["test"] = split2["test"]

drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 605
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 174
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 87
    })
})

In [193]:
drug_dataset_clean.save_to_disk("drug-reviews")

Saving the dataset (0/1 shards):   0%|          | 0/605 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/174 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/87 [00:00<?, ? examples/s]

In [194]:
from datasets import load_from_disk

drug_dataset_reloaded = load_from_disk("drug-reviews")
drug_dataset_reloaded

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 605
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 174
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 87
    })
})

In [195]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

In [196]:
!head -n 1 drug-reviews-train.jsonl

{"patient_id":193154,"drugName":"Dextroamphetamine","condition":"adhd","review":"\"By far the best medication I have tried for ADHD. It is great for someone who also social anxiety or anxiety in general. With Ritalin I had many negative side effects one of which is anxiety. Dexedrine is great. I do not even need to take my clonazepam (Klonopin) during the day because Dexedrine is so smooth.\"","rating":10.0,"date":"October 13, 2010","usefulCount":51,"review_length":57}

In [197]:
data_files = {
    "train": "drug-reviews-train.jsonl",
    "validation": "drug-reviews-validation.jsonl",
    "test": "drug-reviews-test.jsonl",
}
drug_dataset_reloaded = load_dataset("json", data_files=data_files)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [198]:
!pip install zstandard

Requirement already satisfied: zstandard in /Users/yuxinliu/anaconda3/lib/python3.11/site-packages (0.19.0)

In [199]:
from datasets import load_dataset

pubmed_dataset = load_dataset(
    "bigbio/pubmed_qa",
    name="pubmed_qa_labeled_fold0_source",
    split="train",
    trust_remote_code=True
)
pubmed_dataset

Dataset({
    features: ['QUESTION', 'CONTEXTS', 'LABELS', 'MESHES', 'YEAR', 'reasoning_required_pred', 'reasoning_free_pred', 'final_decision', 'LONG_ANSWER'],
    num_rows: 450
})

In [200]:
pubmed_dataset[0]

{'QUESTION': 'Does histologic chorioamnionitis correspond to clinical chorioamnionitis?',
 'CONTEXTS': ['To evaluate the degree to which histologic chorioamnionitis, a frequent finding in placentas submitted for histopathologic evaluation, correlates with clinical indicators of infection in the mother.',
  'A retrospective review was performed on 52 cases with a histologic diagnosis of acute chorioamnionitis from 2,051 deliveries at University Hospital, Newark, from January 2003 to July 2003. Third-trimester placentas without histologic chorioamnionitis (n = 52) served as controls. Cases and controls were selected sequentially. Maternal medical records were reviewed for indicators of maternal infection.',
  'Histologic chorioamnionitis was significantly associated with the usage of antibiotics (p = 0.0095) and a higher mean white blood cell count (p = 0.018). The presence of 1 or more clinical indicators was significantly associated with the presence of histologic chorioamnionitis (p = 0.019).'],
 'LABELS': ['OBJECTIVE', 'STUDY DESIGN', 'RESULTS'],
 'MESHES': ['Adult',
  'Anti-Bacterial Agents',
  'Case-Control Studies',
  'Chorioamnionitis',
  'Diagnosis, Differential',
  'Female',
  'Gestational Age',
  'Humans',
  'Infant, Newborn',
  'Lymphocyte Count',
  'Placenta',
  'Pregnancy',
  'Pregnancy Complications, Infectious',
  'Pregnancy Trimester, Third',
  'Puerperal Infection',
  'Retrospective Studies'],
 'YEAR': '2008',
 'reasoning_required_pred': 'yes',
 'reasoning_free_pred': 'yes',
 'final_decision': 'yes',
 'LONG_ANSWER': 'Histologic chorioamnionitis is a reliable indicator of infection whether or not it is clinically apparent.'}

In [201]:
!pip install psutil

Requirement already satisfied: psutil in /Users/yuxinliu/anaconda3/lib/python3.11/site-packages (5.9.0)

In [202]:
import psutil

print(f"RAM used: {psutil.Process().memory_info().rss / (1024 * 1024): .2f} MB")

RAM used:  42.78 MB

In [203]:
print(f"Dataset size in bytes: {pubmed_dataset.dataset_size}")
size_gb = pubmed_dataset.dataset_size / (1024**3)
print(f"Dataset size (cache file) : {size_gb:.2f} GB")

Dataset size in bytes: 2069809
Dataset size (cache file) : 0.00 GB

In [204]:
import timeit

code_snippet = """batch_size = 1000

for idx in range(0, len(pubmed_dataset), batch_size):
    _ = pubmed_dataset[idx:idx + batch_size]
"""

time = timeit.timeit(stmt=code_snippet, number=1, globals=globals())
print(
    f"Iterated over {len(pubmed_dataset)} examples (about {size_gb:.1f} GB) in "
    f"{time:.1f}s, i.e. {size_gb/time:.3f} GB/s"
)

Iterated over 450 examples (about 0.0 GB) in 0.0s, i.e. 0.209 GB/s

In [205]:
from datasets import load_dataset

pubmed_dataset_streamed = load_dataset(
    "MedRAG/pubmed",
    split="train",
    streaming=True,
    trust_remote_code=True
)

next(iter(pubmed_dataset_streamed))

Resolving data files:   0%|          | 0/1166 [00:00<?, ?it/s]

{'id': 'pubmed23n0001_0',
 'title': "[Biochemical studies on camomile components/III. In vitro studies about the antipeptic activity of (--)-alpha-bisabolol (author's transl)].",
 'content': '(--)-alpha-Bisabolol has a primary antipeptic action depending on dosage, which is not caused by an alteration of the pH-value. The proteolytic activity of pepsin is reduced by 50 percent through addition of bisabolol in the ratio of 1/0.5. The antipeptic action of bisabolol only occurs in case of direct contact. In case of a previous contact with the substrate, the inhibiting effect is lost.',
 'contents': "[Biochemical studies on camomile components/III. In vitro studies about the antipeptic activity of (--)-alpha-bisabolol (author's transl)]. (--)-alpha-Bisabolol has a primary antipeptic action depending on dosage, which is not caused by an alteration of the pH-value. The proteolytic activity of pepsin is reduced by 50 percent through addition of bisabolol in the ratio of 1/0.5. The antipeptic action of bisabolol only occurs in case of direct contact. In case of a previous contact with the substrate, the inhibiting effect is lost.",
 'PMID': 21}

In [206]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
tokenized_dataset = pubmed_dataset_streamed.map(lambda x: tokenizer(x["contents"]))
next(iter(tokenized_dataset))

{'id': 'pubmed23n0001_0',
 'title': "[Biochemical studies on camomile components/III. In vitro studies about the antipeptic activity of (--)-alpha-bisabolol (author's transl)].",
 'content': '(--)-alpha-Bisabolol has a primary antipeptic action depending on dosage, which is not caused by an alteration of the pH-value. The proteolytic activity of pepsin is reduced by 50 percent through addition of bisabolol in the ratio of 1/0.5. The antipeptic action of bisabolol only occurs in case of direct contact. In case of a previous contact with the substrate, the inhibiting effect is lost.',
 'contents': "[Biochemical studies on camomile components/III. In vitro studies about the antipeptic activity of (--)-alpha-bisabolol (author's transl)]. (--)-alpha-Bisabolol has a primary antipeptic action depending on dosage, which is not caused by an alteration of the pH-value. The proteolytic activity of pepsin is reduced by 50 percent through addition of bisabolol in the ratio of 1/0.5. The antipeptic action of bisabolol only occurs in case of direct contact. In case of a previous contact with the substrate, the inhibiting effect is lost.",
 'PMID': 21,
 'input_ids': [101,
  1031,
  16012,
  15869,
  2913,
  2006,
  11503,
  20936,
  2571,
  6177,
  1013,
  3523,
  1012,
  1999,
  25714,
  2913,
  2055,
  1996,
  3424,
  5051,
  20746,
  4023,
  1997,
  1006,
  1011,
  1011,
  1007,
  1011,
  6541,
  1011,
  20377,
  7875,
  12898,
  2140,
  1006,
  3166,
  1005,
  1055,
  9099,
  2140,
  1007,
  1033,
  1012,
  1006,
  1011,
  1011,
  1007,
  1011,
  6541,
  1011,
  20377,
  7875,
  12898,
  2140,
  2038,
  1037,
  3078,
  3424,
  5051,
  20746,
  2895,
  5834,
  2006,
  9998,
  4270,
  1010,
  2029,
  2003,
  2025,
  3303,
  2011,
  2019,
  26014,
  1997,
  1996,
  6887,
  1011,
  3643,
  1012,
  1996,
  4013,
  2618,
  4747,
  21252,
  4023,
  1997,
  27237,
  2078,
  2003,
  4359,
  2011,
  2753,
  3867,
  2083,
  2804,
  1997,
  20377,
  7875,
  12898,
  2140,
  1999,
  1996,
  6463,
  1997,
  1015,
  1013,
  1014,
  1012,
  1019,
  1012,
  1996,
  3424,
  5051,
  20746,
  2895,
  1997,
  20377,
  7875,
  12898,
  2140,
  2069,
  5158,
  1999,
  2553,
  1997,
  3622,
  3967,
  1012,
  1999,
  2553,
  1997,
  1037,
  3025,
  3967,
  2007,
  1996,
  16305,
  1010,
  1996,
  26402,
  2075,
  3466,
  2003,
  2439,
  1012,
  102],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

In [207]:
shuffled_dataset = pubmed_dataset_streamed.shuffle(buffer_size=10000, seed=42)
next(iter(shuffled_dataset))

{'id': 'pubmed23n0070_892',
 'title': 'Evaluation of four commercial anaerobic systems for identification of Eubacterium suis.',
 'content': 'Four commercial anaerobic systems (CASs) were evaluated for usefulness in identification of Eubacterium suis. Twelve strains were evaluated in each system in triplicate, and results were interpreted independently by 5 individuals. Statistically significant differences (P less than 0.01) due to strain variation and reader interpretation accounted for discrepancies encountered. The reactivity, repeatability, and unique profiles generated made both CAS-1 and CAS-2 suitable adjuncts for identification of E. suis when colony morphology and Gram reaction were considered. Limited reactivity in CAS-3 limited its use as an aid in identification. Variability in test observations and the large number of numerical profiles generated precluded use of CAS-4.',
 'contents': 'Evaluation of four commercial anaerobic systems for identification of Eubacterium suis. Four commercial anaerobic systems (CASs) were evaluated for usefulness in identification of Eubacterium suis. Twelve strains were evaluated in each system in triplicate, and results were interpreted independently by 5 individuals. Statistically significant differences (P less than 0.01) due to strain variation and reader interpretation accounted for discrepancies encountered. The reactivity, repeatability, and unique profiles generated made both CAS-1 and CAS-2 suitable adjuncts for identification of E. suis when colony morphology and Gram reaction were considered. Limited reactivity in CAS-3 limited its use as an aid in identification. Variability in test observations and the large number of numerical profiles generated precluded use of CAS-4.',
 'PMID': 2095281}

In [208]:
dataset_head = pubmed_dataset_streamed.take(5)
list(dataset_head)

[{'id': 'pubmed23n0001_0',
  'title': "[Biochemical studies on camomile components/III. In vitro studies about the antipeptic activity of (--)-alpha-bisabolol (author's transl)].",
  'content': '(--)-alpha-Bisabolol has a primary antipeptic action depending on dosage, which is not caused by an alteration of the pH-value. The proteolytic activity of pepsin is reduced by 50 percent through addition of bisabolol in the ratio of 1/0.5. The antipeptic action of bisabolol only occurs in case of direct contact. In case of a previous contact with the substrate, the inhibiting effect is lost.',
  'contents': "[Biochemical studies on camomile components/III. In vitro studies about the antipeptic activity of (--)-alpha-bisabolol (author's transl)]. (--)-alpha-Bisabolol has a primary antipeptic action depending on dosage, which is not caused by an alteration of the pH-value. The proteolytic activity of pepsin is reduced by 50 percent through addition of bisabolol in the ratio of 1/0.5. The antipeptic action of bisabolol only occurs in case of direct contact. In case of a previous contact with the substrate, the inhibiting effect is lost.",
  'PMID': 21},
 {'id': 'pubmed23n0001_1',
  'title': '[Demonstration of tumor inhibiting properties of a strongly immunostimulating low-molecular weight substance. Comparative studies with ifosfamide on the immuno-labile DS carcinosarcoma. Stimulation of the autoimmune activity for approx. 20 days by BA 1, a N-(2-cyanoethylene)-urea. Novel prophylactic possibilities].',
  'content': 'A report is given on the recent discovery of outstanding immunological properties in BA 1 [N-(2-cyanoethylene)-urea] having a (low) molecular mass M = 111.104. Experiments in 214 DS carcinosarcoma bearing Wistar rats have shown that BA 1, at a dosage of only about 12 percent LD50 (150 mg kg) and negligible lethality (1.7 percent), results in a recovery rate of 40 percent without hyperglycemia and, in one test, of 80 percent with hyperglycemia. Under otherwise unchanged conditions the reference substance ifosfamide (IF) -- a further development of cyclophosphamide -- applied without hyperglycemia in its most efficient dosage of 47 percent LD50 (150 mg kg) brought about a recovery rate of 25 percent at a lethality of 18 percent. (Contrary to BA 1, 250-min hyperglycemia caused no further improvement of the recovery rate.) However this comparison is characterized by the fact that both substances exhibit two quite different (complementary) mechanisms of action. Leucocyte counts made after application of the said cancerostatics and dosages have shown a pronounced stimulation with BA 1 and with ifosfamide, the known suppression in the post-therapeutic interval usually found with standard cancerostatics. In combination with the cited plaque test for BA 1, blood pictures then allow conclusions on the immunity status. Since IF can be taken as one of the most efficient cancerostatics--there is no other chemotherapeutic known up to now that has a more significant effect on the DS carcinosarcoma in rats -- these findings are of special importance. Finally, the total amount of leucocytes and lymphocytes as well as their time behaviour was determined from the blood picture of tumour-free rats after i.v. application of BA 1. The thus obtained numerical values clearly show that further research work on the prophylactic use of this substance seems to be necessary and very promising.',
  'contents': '[Demonstration of tumor inhibiting properties of a strongly immunostimulating low-molecular weight substance. Comparative studies with ifosfamide on the immuno-labile DS carcinosarcoma. Stimulation of the autoimmune activity for approx. 20 days by BA 1, a N-(2-cyanoethylene)-urea. Novel prophylactic possibilities]. A report is given on the recent discovery of outstanding immunological properties in BA 1 [N-(2-cyanoethylene)-urea] having a (low) molecular mass M = 111.104. Experiments in 214 DS carcinosarcoma bearing Wistar rats have shown that BA 1, at a dosage of only about 12 percent LD50 (150 mg kg) and negligible lethality (1.7 percent), results in a recovery rate of 40 percent without hyperglycemia and, in one test, of 80 percent with hyperglycemia. Under otherwise unchanged conditions the reference substance ifosfamide (IF) -- a further development of cyclophosphamide -- applied without hyperglycemia in its most efficient dosage of 47 percent LD50 (150 mg kg) brought about a recovery rate of 25 percent at a lethality of 18 percent. (Contrary to BA 1, 250-min hyperglycemia caused no further improvement of the recovery rate.) However this comparison is characterized by the fact that both substances exhibit two quite different (complementary) mechanisms of action. Leucocyte counts made after application of the said cancerostatics and dosages have shown a pronounced stimulation with BA 1 and with ifosfamide, the known suppression in the post-therapeutic interval usually found with standard cancerostatics. In combination with the cited plaque test for BA 1, blood pictures then allow conclusions on the immunity status. Since IF can be taken as one of the most efficient cancerostatics--there is no other chemotherapeutic known up to now that has a more significant effect on the DS carcinosarcoma in rats -- these findings are of special importance. Finally, the total amount of leucocytes and lymphocytes as well as their time behaviour was determined from the blood picture of tumour-free rats after i.v. application of BA 1. The thus obtained numerical values clearly show that further research work on the prophylactic use of this substance seems to be necessary and very promising.',
  'PMID': 22},
 {'id': 'pubmed23n0001_2',
  'title': 'Effect of etafenone on total and regional myocardial blood flow.',
  'content': 'The distribution of blood flow to the subendocardial, medium and subepicardial layers of the left ventricular free wall was studied in anaesthetized dogs under normoxic (A), hypoxic (B) conditions and under pharmacologically induced (etafenone) coronary vasodilation (C). Regional myocardial blood flow was determined by means of the particle distribution method. In normoxia a transmural gradient of flow was observed, with the subendocardial layers receiving a significantly higher flow rate compared with the subepicardial layers. In hypoxia induced vasodilation this transmural gradient of flow was persistent. In contrast a marked redistribution of regional flow was observed under pharmacologically induced vasodilation. The transmural gradient decreased. In contrast to some findings these experiments demonstrate that a considerable vasodilatory capacity exists in all layers of the myocardium and can be utilized by drugs. The differences observed for the intramural distribution pattern of flow under hypoxia and drug induced vasodilation support the hypothesis that this pattern reflects corresponding gradients of regional myocardial metabolism.',
  'contents': 'Effect of etafenone on total and regional myocardial blood flow. The distribution of blood flow to the subendocardial, medium and subepicardial layers of the left ventricular free wall was studied in anaesthetized dogs under normoxic (A), hypoxic (B) conditions and under pharmacologically induced (etafenone) coronary vasodilation (C). Regional myocardial blood flow was determined by means of the particle distribution method. In normoxia a transmural gradient of flow was observed, with the subendocardial layers receiving a significantly higher flow rate compared with the subepicardial layers. In hypoxia induced vasodilation this transmural gradient of flow was persistent. In contrast a marked redistribution of regional flow was observed under pharmacologically induced vasodilation. The transmural gradient decreased. In contrast to some findings these experiments demonstrate that a considerable vasodilatory capacity exists in all layers of the myocardium and can be utilized by drugs. The differences observed for the intramural distribution pattern of flow under hypoxia and drug induced vasodilation support the hypothesis that this pattern reflects corresponding gradients of regional myocardial metabolism.',
  'PMID': 23},
 {'id': 'pubmed23n0001_3',
  'title': 'Influence of a new virostatic compound on the induction of enzymes in rat liver.',
  'content': 'The virostatic compound N,N-diethyl-4-[2-(2-oxo-3-tetradecyl-1-imidazolidinyl)-ethyl]-1-piperazinecarboxamide-hydrochloride (5531) was analyzed as to its effect on the induction of tryptophan-pyrrolase and tyrosineaminotransferase in rat liver. 1. The basic activity of the enzymes was not influenced by the substance either in normal or in adrenalectomized animals. 2. The induction of the enzymes by cortisone increased in the presence of the compound whereas the substrate induction remained unchanged. 3. The induction of tyrosine-aminotransferase by dexamethasonephosphate in tissue culture is inhibited if the dose of compound 5531 is higher than 5 mug/ml.',
  'contents': 'Influence of a new virostatic compound on the induction of enzymes in rat liver. The virostatic compound N,N-diethyl-4-[2-(2-oxo-3-tetradecyl-1-imidazolidinyl)-ethyl]-1-piperazinecarboxamide-hydrochloride (5531) was analyzed as to its effect on the induction of tryptophan-pyrrolase and tyrosineaminotransferase in rat liver. 1. The basic activity of the enzymes was not influenced by the substance either in normal or in adrenalectomized animals. 2. The induction of the enzymes by cortisone increased in the presence of the compound whereas the substrate induction remained unchanged. 3. The induction of tyrosine-aminotransferase by dexamethasonephosphate in tissue culture is inhibited if the dose of compound 5531 is higher than 5 mug/ml.',
  'PMID': 24},
 {'id': 'pubmed23n0001_4',
  'title': 'Pharmacological properties of new neuroleptic compounds.',
  'content': "RMI 61 140, RMI 61 144 and RMI 61 280 are newly synthetized N-[8-R-dibenzo(b,f)oxepin-10-yl]-N'-methyl-piperazine-maleates which show interesting psychopharmacologic effects. This work contains the results of a study performed with these three compounds, in order to demonstrate their neuropsycholeptic activity in comparison with chloropromazine (CPZ) and chlordiazepoxide (CPD). The inhibition of motility observed in mice shows that the compounds reduce the normal spontaneous motility as well as the muscle tone. The central-depressant activity is evidenced by increased barbiturate-induced sleep and a remarkable eyelid ptosis can also be observed. Our compounds do not show any activity on electroshock just as do CPZ and CPD. As to the antipsychotic outline, our compounds show strong reduction of lethality due to amphetamine in grouped mice and a strong antiapomorphine activity. They show also an antiaggressive effect and an inhibitory activity on avoidance behaviour much stronger than CPZ. We have also found extrapyramidal effects, as catalepsy, common to many tranquillizers of the kind of the standards used by us. As for vegetative phenomena, the compounds show hypotensive dose related action ranging from moderate to strong, probably due to an a-receptor inhibition. Adrenolytic activity against lethal doses of adrenaline, antiserotonin and antihistaminic effects, as well as other actions (hypothermia, analgesia, etc.) confirm that RMI 61 140, RMI 61 144 and RMI 61 280 are endowed with pharmacologic properties similar and more potent than those of CPZ. Studies on the metabolism of brain catecholamines show that they are similar to CPZ, although with less effect on dopamine level.",
  'contents': "Pharmacological properties of new neuroleptic compounds. RMI 61 140, RMI 61 144 and RMI 61 280 are newly synthetized N-[8-R-dibenzo(b,f)oxepin-10-yl]-N'-methyl-piperazine-maleates which show interesting psychopharmacologic effects. This work contains the results of a study performed with these three compounds, in order to demonstrate their neuropsycholeptic activity in comparison with chloropromazine (CPZ) and chlordiazepoxide (CPD). The inhibition of motility observed in mice shows that the compounds reduce the normal spontaneous motility as well as the muscle tone. The central-depressant activity is evidenced by increased barbiturate-induced sleep and a remarkable eyelid ptosis can also be observed. Our compounds do not show any activity on electroshock just as do CPZ and CPD. As to the antipsychotic outline, our compounds show strong reduction of lethality due to amphetamine in grouped mice and a strong antiapomorphine activity. They show also an antiaggressive effect and an inhibitory activity on avoidance behaviour much stronger than CPZ. We have also found extrapyramidal effects, as catalepsy, common to many tranquillizers of the kind of the standards used by us. As for vegetative phenomena, the compounds show hypotensive dose related action ranging from moderate to strong, probably due to an a-receptor inhibition. Adrenolytic activity against lethal doses of adrenaline, antiserotonin and antihistaminic effects, as well as other actions (hypothermia, analgesia, etc.) confirm that RMI 61 140, RMI 61 144 and RMI 61 280 are endowed with pharmacologic properties similar and more potent than those of CPZ. Studies on the metabolism of brain catecholamines show that they are similar to CPZ, although with less effect on dopamine level.",
  'PMID': 25}]

In [209]:
train_dataset = shuffled_dataset.skip(1000)
validation_dataset = shuffled_dataset.take(500)

In [210]:
!pip install requests

Requirement already satisfied: requests in /Users/yuxinliu/anaconda3/lib/python3.11/site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/yuxinliu/anaconda3/lib/python3.11/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/yuxinliu/anaconda3/lib/python3.11/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/yuxinliu/anaconda3/lib/python3.11/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/yuxinliu/anaconda3/lib/python3.11/site-packages (from requests) (2025.10.5)

In [211]:
import requests

url = "https://api.github.com/repos/huggingface/datasets/issues?page=1&per_page=1"
response = requests.get(url)

In [212]:
response.status_code

403

In [213]:
response.json()

{'message': "API rate limit exceeded for 138.246.3.108. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}

In [214]:
import os
import time
import math
import requests
import pandas as pd
from pathlib import Path
from tqdm.notebook import tqdm

# 先删旧文件
if os.path.exists("datasets-issues.jsonl"):
    os.remove("datasets-issues.jsonl")
    print("deleted old file")

HEADERS = {"Authorization": "Bearer token"}

def fetch_issues(
    owner="huggingface",
    repo="datasets",
    num_issues=10_000,
    rate_limit=5_000,
    issues_path=Path("."),
):
    if not issues_path.is_dir():
        issues_path.mkdir(exist_ok=True)

    batch = []
    all_issues = []
    per_page = 100
    num_pages = math.ceil(num_issues / per_page)
    base_url = "https://api.github.com/repos"

    for page in tqdm(range(num_pages)):
        query = f"issues?page={page}&per_page={per_page}&state=all"
        response = requests.get(f"{base_url}/{owner}/{repo}/{query}", headers=HEADERS)
        data = response.json()

        if isinstance(data, dict): 
            print(f"API Error page {page}: {data}")
            break

        batch.extend(data)

        if len(batch) > rate_limit and len(all_issues) < num_issues:
            all_issues.extend(batch)
            batch = []
            print("Rate limit reached, sleeping...")
            time.sleep(60 * 60 + 1)

    all_issues.extend(batch)
    df = pd.DataFrame.from_records(all_issues)
    df.to_json(f"{issues_path}/{repo}-issues.jsonl", orient="records", lines=True)
    print(f"Done! {len(df)} issues saved.")

In [215]:
fetch_issues(num_issues=1_000)

  0%|          | 0/10 [00:00<?, ?it/s]

Downloaded all the issues for datasets! Dataset stored at ./datasets-issues.jsonl

In [225]:
issues_dataset = load_dataset("json", data_files="datasets-issues.jsonl", split="train")
issues_dataset

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'assignee', 'author_association', 'issue_field_values', 'type', 'active_lock_reason', 'draft', 'pull_request', 'body', 'closed_by', 'reactions', 'timeline_url', 'performed_via_github_app', 'state_reason', 'sub_issues_summary', 'issue_dependencies_summary', 'pinned_comment'],
    num_rows: 1000
})

In [226]:
sample = issues_dataset.shuffle(seed=666).select(range(3))

for url, pr in zip(sample["html_url"], sample["pull_request"]):
    print(f">> URL: {url}")
    print(f">> PULL request: {pr}")

>> URL: https://github.com/huggingface/datasets/pull/8135
>> PULL request: {'url': 'https://api.github.com/repos/huggingface/datasets/pulls/8135', 'html_url': 'https://github.com/huggingface/datasets/pull/8135', 'diff_url': 'https://github.com/huggingface/datasets/pull/8135.diff', 'patch_url': 'https://github.com/huggingface/datasets/pull/8135.patch', 'merged_at': None}
>> URL: https://github.com/huggingface/datasets/pull/8166
>> PULL request: {'url': 'https://api.github.com/repos/huggingface/datasets/pulls/8166', 'html_url': 'https://github.com/huggingface/datasets/pull/8166', 'diff_url': 'https://github.com/huggingface/datasets/pull/8166.diff', 'patch_url': 'https://github.com/huggingface/datasets/pull/8166.patch', 'merged_at': datetime.datetime(2026, 4, 30, 15, 38, 42)}
>> URL: https://github.com/huggingface/datasets/issues/7388
>> PULL request: None

In [227]:
print(issues_dataset[0])
print(issues_dataset.column_names)

{'url': 'https://api.github.com/repos/huggingface/datasets/issues/8195', 'repository_url': 'https://api.github.com/repos/huggingface/datasets', 'labels_url': 'https://api.github.com/repos/huggingface/datasets/issues/8195/labels{/name}', 'comments_url': 'https://api.github.com/repos/huggingface/datasets/issues/8195/comments', 'events_url': 'https://api.github.com/repos/huggingface/datasets/issues/8195/events', 'html_url': 'https://github.com/huggingface/datasets/pull/8195', 'id': 4428413094, 'node_id': 'PR_kwDODunzps7aombr', 'number': 8195, 'title': 'Fix spurious label column when folder builders see split-named directories', 'user': {'login': '1fanwang', 'id': 21269208, 'node_id': 'MDQ6VXNlcjIxMjY5MjA4', 'avatar_url': 'https://avatars.githubusercontent.com/u/21269208?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/1fanwang', 'html_url': 'https://github.com/1fanwang', 'followers_url': 'https://api.github.com/users/1fanwang/followers', 'following_url': 'https://api.github.com/users/1fanwang/following{/other_user}', 'gists_url': 'https://api.github.com/users/1fanwang/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/1fanwang/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/1fanwang/subscriptions', 'organizations_url': 'https://api.github.com/users/1fanwang/orgs', 'repos_url': 'https://api.github.com/users/1fanwang/repos', 'events_url': 'https://api.github.com/users/1fanwang/events{/privacy}', 'received_events_url': 'https://api.github.com/users/1fanwang/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': datetime.datetime(2026, 5, 12, 10, 45, 35), 'updated_at': datetime.datetime(2026, 5, 12, 10, 45, 35), 'closed_at': None, 'assignee': None, 'author_association': 'NONE', 'issue_field_values': [], 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/huggingface/datasets/pulls/8195', 'html_url': 'https://github.com/huggingface/datasets/pull/8195', 'diff_url': 'https://github.com/huggingface/datasets/pull/8195.diff', 'patch_url': 'https://github.com/huggingface/datasets/pull/8195.patch', 'merged_at': None}, 'body': 'Closes #7880.\n\n## What\n\n`folder_based_builder._split_generators` allocates a single `labels: set[str]` outside the per-split loop and `analyze(...)` mutates it across every split. When the user passes:\n\n```python\nload_dataset("audiofolder", data_files={"train": "train/**", "test": "test/**"})\n```\n\nand the actual files live directly under `train/` and `test/` (no per-class subdirs), the parent-dir-name accumulator ends up with `labels = {"train", "test"}`. The `add_labels = len(labels) > 1 and len(path_depths) == 1` heuristic then flips True and the loader silently adds a `ClassLabel(names=[\'test\', \'train\'])` column. Worse, `add_labels` is recomputed per split inside the loop while features get set once after, so the first split\'s examples are emitted with `label=None` — which downstream `int2str(None)` then trips over.\n\nThe fix adds a single check: if the inferred label set is a subset of the user-declared split names, treat it as splits-not-classes and skip label inference. `drop_labels=False` (the explicit opt-in to label inference) is preserved.\n\n## How is this tested?\n\nNew fixture `data_files_with_split_dirs_no_metadata` builds `train/` + `test/` dirs without class subdirs. Parametrized test:\n\n- default → no `label` column\n- `drop_labels=True` → no `label` column\n- `drop_labels=False` → ClassLabel still produced with `names=[\'test\', \'train\']` (opt-in preserved)\n\nThe test fails on `main` with both the spurious column and the `int2str(None)` crash on `drop_labels=False` (mis-emitted label=None). It passes with this PR.\n\nFull `tests/packaged_modules/test_folder_based_builder.py` (49 tests), `test_imagefolder.py` (36), `test_videofolder.py` (8), and `test_data_files.py` (224) all pass. `make quality` + `make style` clean.\n\n`test_audiofolder.py` has 11 pre-existing `torchcodec`/`libavutil` failures on `main` that are unrelated to this change.', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/8195/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/huggingface/datasets/issues/8195/timeline', 'performed_via_github_app': None, 'state_reason': None, 'sub_issues_summary': None, 'issue_dependencies_summary': None, 'pinned_comment': None}
['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'assignee', 'author_association', 'issue_field_values', 'type', 'active_lock_reason', 'draft', 'pull_request', 'body', 'closed_by', 'reactions', 'timeline_url', 'performed_via_github_app', 'state_reason', 'sub_issues_summary', 'issue_dependencies_summary', 'pinned_comment']

In [228]:
issues_dataset = issues_dataset.map(
    lambda x: {"is_pull_request": False if x["pull_request"] is None else True}
)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [229]:
issue_number = 2792
url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
response = requests.get(url, headers=headers)
response.json()

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/897594128',
  'html_url': 'https://github.com/huggingface/datasets/pull/2792#issuecomment-897594128',
  'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/2792',
  'id': 897594128,
  'node_id': 'IC_kwDODunzps41gDMQ',
  'user': {'login': 'bhavitvyamalik',
   'id': 19718818,
   'node_id': 'MDQ6VXNlcjE5NzE4ODE4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19718818?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bhavitvyamalik',
   'html_url': 'https://github.com/bhavitvyamalik',
   'followers_url': 'https://api.github.com/users/bhavitvyamalik/followers',
   'following_url': 'https://api.github.com/users/bhavitvyamalik/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bhavitvyamalik/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bhavitvyamalik/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bhavitvyamalik/subscriptions',
   'organizations_url': 'https://api.github.com/users/bhavitvyamalik/orgs',
   'repos_url': 'https://api.github.com/users/bhavitvyamalik/repos',
   'events_url': 'https://api.github.com/users/bhavitvyamalik/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bhavitvyamalik/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'created_at': '2021-08-12T12:21:52Z',
  'updated_at': '2021-08-12T12:31:17Z',
  'body': "@albertvillanova my tests are failing here:\r\n```\r\ndataset_name = 'gooaq'\r\n\r\n    def test_load_dataset(self, dataset_name):\r\n        configs = self.dataset_tester.load_all_configs(dataset_name, is_local=True)[:1]\r\n>       self.dataset_tester.check_load_dataset(dataset_name, configs, is_local=True, use_local_dummy_data=True)\r\n\r\ntests/test_dataset_common.py:234: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\ntests/test_dataset_common.py:187: in check_load_dataset\r\n    self.parent.assertTrue(len(dataset[split]) > 0)\r\nE   AssertionError: False is not true\r\n```\r\nWhen I try loading dataset on local machine it works fine. Any suggestions on how can I avoid this error?",
  'author_association': 'CONTRIBUTOR',
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/897594128/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/898644889',
  'html_url': 'https://github.com/huggingface/datasets/pull/2792#issuecomment-898644889',
  'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/2792',
  'id': 898644889,
  'node_id': 'IC_kwDODunzps41kDuZ',
  'user': {'login': 'bhavitvyamalik',
   'id': 19718818,
   'node_id': 'MDQ6VXNlcjE5NzE4ODE4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19718818?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bhavitvyamalik',
   'html_url': 'https://github.com/bhavitvyamalik',
   'followers_url': 'https://api.github.com/users/bhavitvyamalik/followers',
   'following_url': 'https://api.github.com/users/bhavitvyamalik/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bhavitvyamalik/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bhavitvyamalik/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bhavitvyamalik/subscriptions',
   'organizations_url': 'https://api.github.com/users/bhavitvyamalik/orgs',
   'repos_url': 'https://api.github.com/users/bhavitvyamalik/repos',
   'events_url': 'https://api.github.com/users/bhavitvyamalik/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bhavitvyamalik/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'created_at': '2021-08-13T18:28:27Z',
  'updated_at': '2021-08-13T18:28:27Z',
  'body': 'Thanks for the help, @albertvillanova! All tests are passing now.',
  'author_association': 'CONTRIBUTOR',
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/898644889/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'performed_via_github_app': None}]

In [230]:
def get_comments(issue_number):
    url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
    response = requests.get(url, headers=HEADERS)
    return [r["body"] for r in response.json()]

get_comments(2792)

["@albertvillanova my tests are failing here:\r\n```\r\ndataset_name = 'gooaq'\r\n\r\n    def test_load_dataset(self, dataset_name):\r\n        configs = self.dataset_tester.load_all_configs(dataset_name, is_local=True)[:1]\r\n>       self.dataset_tester.check_load_dataset(dataset_name, configs, is_local=True, use_local_dummy_data=True)\r\n\r\ntests/test_dataset_common.py:234: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\ntests/test_dataset_common.py:187: in check_load_dataset\r\n    self.parent.assertTrue(len(dataset[split]) > 0)\r\nE   AssertionError: False is not true\r\n```\r\nWhen I try loading dataset on local machine it works fine. Any suggestions on how can I avoid this error?",
 'Thanks for the help, @albertvillanova! All tests are passing now.']

In [231]:
issues_dataset = issues_dataset.map(
    lambda x: {"comments": get_comments(x["number"])}
)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

In [ ]:
# issues_with_comments_dataset.push_to_hub("github-issues")

In [ ]:
# remote_dataset = load_dataset("lewton/github-issues", split="train")
# remote_dataset

In [248]:
from datasets import load_dataset

issues_dataset = load_dataset("lewtun/github-issues", split="train")

Repo card metadata block was not found. Setting CardData to empty.

In [249]:
issues_dataset

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason', 'pull_request', 'body', 'timeline_url', 'performed_via_github_app', 'is_pull_request'],
    num_rows: 3019
})

In [250]:
issues_dataset = issues_dataset.filter(
    lambda x: (x["is_pull_request"] == False and len(x["comments"]) > 0)
)
issues_dataset

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason', 'pull_request', 'body', 'timeline_url', 'performed_via_github_app', 'is_pull_request'],
    num_rows: 808
})

In [251]:
columns = issues_dataset.column_names
columns_to_keep = ["title", "body", "html_url", "comments"]
columns_to_remove = set(columns_to_keep).symmetric_difference(columns)
issues_dataset = issues_dataset.remove_columns(columns_to_remove)
issues_dataset

Dataset({
    features: ['html_url', 'title', 'comments', 'body'],
    num_rows: 808
})

In [254]:
issues_dataset.set_format("pandas")
df = issues_dataset[:]

In [255]:
df["comments"][0].tolist()

['Cool, I think we can do both :)',
 '@lhoestq now the 2 are implemented.\r\n\r\nPlease note that for the the second protection, finally I have chosen to protect the master branch only from **merge commits** (see update comment above), so no need to disable/re-enable the protection on each release (direct commits, different from merge commits, can be pushed to the remote master branch; and eventually reverted without messing up the repo history).']

In [256]:
comments_df = df.explode("comments", ignore_index=True)
comments_df.head(4)

,html_url,title,comments,body
0,https://github.com/huggingface/datasets/issues...,Protect master branch,"Cool, I think we can do both :)",After accidental merge commit (91c55355b634d0d...
1,https://github.com/huggingface/datasets/issues...,Protect master branch,@lhoestq now the 2 are implemented.\r\n\r\nPle...,After accidental merge commit (91c55355b634d0d...
2,https://github.com/huggingface/datasets/issues...,Backwards compatibility broken for cached data...,Hi ! I guess the caching mechanism should have...,## Describe the bug\r\nAfter upgrading to data...
3,https://github.com/huggingface/datasets/issues...,Backwards compatibility broken for cached data...,"If it's easy enough to implement, then yes ple...",## Describe the bug\r\nAfter upgrading to data...

In [257]:
from datasets import Dataset

comments_dataset = Dataset.from_pandas(comments_df)
comments_dataset

Dataset({
    features: ['html_url', 'title', 'comments', 'body'],
    num_rows: 2964
})

In [258]:
comments_dataset = comments_dataset.map(
    lambda x: {"comments_length": len(x["comments"].split())}
)

Map:   0%|          | 0/2964 [00:00<?, ? examples/s]

In [259]:
comments_dataset = comments_dataset.filter(lambda x: x["comments_length"] > 15)
comments_dataset

Filter:   0%|          | 0/2964 [00:00<?, ? examples/s]

Dataset({
    features: ['html_url', 'title', 'comments', 'body', 'comments_length'],
    num_rows: 2175
})

In [260]:
def concatenate_text(examples):
    return {
        "text": examples["title"] + " \n" + examples["body"] + " \n " + examples["comments"]
    }

comments_dataset = comments_dataset.map(concatenate_text)

Map:   0%|          | 0/2175 [00:00<?, ? examples/s]

In [261]:
from transformers import AutoTokenizer, AutoModel

model_ckpt = "sentence-transformers/multi-qa-mpnet-base-dot-v1"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
model = AutoModel.from_pretrained(model_ckpt)

'(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: bf5e2cdd-bf88-4fad-a402-902a1c953c2a)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/multi-qa-mpnet-base-dot-v1/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

In [262]:
import torch
device = torch.device("mps")
model.to(device)

MPNetModel(
  (embeddings): MPNetEmbeddings(
    (word_embeddings): Embedding(30527, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): MPNetEncoder(
    (layer): ModuleList(
      (0-11): 12 x MPNetLayer(
        (attention): MPNetAttention(
          (attn): MPNetSelfAttention(
            (q): Linear(in_features=768, out_features=768, bias=True)
            (k): Linear(in_features=768, out_features=768, bias=True)
            (v): Linear(in_features=768, out_features=768, bias=True)
            (o): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (intermediate): MPNetIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): MPNetOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (relative_attention_bias): Embedding(32, 12)
  )
  (pooler): MPNetPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [266]:
def cls_pooling(model_output):
    return model_output.last_hidden_state[:, 0]

In [269]:
def get_embeddings(text_list):
    encoded_input = tokenizer(text_list, padding=True, truncation=True, return_tensors="pt")
    encoded_input = {k: v.to(device) for k, v in encoded_input.items()}
    model_output = model(**encoded_input)
    return cls_pooling(model_output)

In [270]:
embedding = get_embeddings(comments_dataset["text"][0])
embedding.shape

torch.Size([1, 768])

In [271]:
embeddings_dataset = comments_dataset.map(
    lambda x: {"embeddings": get_embeddings(x["text"]).detach().cpu().numpy()[0]}
)

Map:   0%|          | 0/2175 [00:00<?, ? examples/s]

In [277]:
embeddings_dataset.add_faiss_index(column="embeddings")

ImportError: You must install Faiss to use FaissIndex. To do so you can run `conda install -c pytorch faiss-cpu` or `conda install -c pytorch faiss-gpu`. A community supported package is also available on pypi: `pip install faiss-cpu` or `pip install faiss-gpu`. Note that pip may not have the latest version of FAISS, and thus, some of the latest features and bug fixes may not be available.

In [278]:
question = "How can I load a dataset offline?"
question_embedding = get_embeddings([question]).detach().cpu().numpy()
question_embedding.shape

(1, 768)

In [279]:
scores, samples = embeddings_dataset.get_nearest_examples("embeddings", question_embedding, k=5)

MissingIndex: Index with index_name 'embeddings' not initialized yet. Please make sure that you call `add_faiss_index` or `add_elasticsearch_index` first.

In [286]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def search_without_faiss(query_embedding, embeddings, k=5):
    query_embedding = np.array(query_embedding).squeeze()  # 确保是 1D
    scores = cosine_similarity([query_embedding], embeddings)[0]
    top_k = np.argsort(scores)[::-1][:k]
    return top_k, scores[top_k]

embeddings_matrix = np.array(embeddings_dataset["embeddings"])
top_k_indices, top_k_scores = search_without_faiss(
    query_embedding=question_embedding,
    embeddings=embeddings_matrix,
    k=5
)

samples = embeddings_dataset.select(top_k_indices)

In [288]:
samples[:3]

{'html_url': ['https://github.com/huggingface/datasets/issues/824',
  'https://github.com/huggingface/datasets/issues/824',
  'https://github.com/huggingface/datasets/issues/824'],
 'title': ['Discussion using datasets in offline mode',
  'Discussion using datasets in offline mode',
  'Discussion using datasets in offline mode'],
 'comments': ['here is my way to load a dataset offline, but it **requires** an online machine\r\n1. (online machine)\r\n```\r\nimport datasets\r\ndata = datasets.load_dataset(...)\r\ndata.save_to_disk(/YOUR/DATASET/DIR)\r\n```\r\n2. copy the dir from online to the offline machine\r\n3. (offline machine)\r\n```\r\nimport datasets\r\ndata = datasets.load_from_disk(/SAVED/DATA/DIR)\r\n```\r\n\r\nHTH.',
  '> here is my way to load a dataset offline, but it **requires** an online machine\n> \n> 1. (online machine)\n> \n> ```\n> \n> import datasets\n> \n> data = datasets.load_dataset(...)\n> \n> data.save_to_disk(/YOUR/DATASET/DIR)\n> \n> ```\n> \n> 2. copy the dir from online to the offline machine\n> \n> 3. (offline machine)\n> \n> ```\n> \n> import datasets\n> \n> data = datasets.load_from_disk(/SAVED/DATA/DIR)\n> \n> ```\n> \n> \n> \n> HTH.\n\n',
  'I opened a PR that allows to reload modules that have already been loaded once even if there\'s no internet.\r\n\r\nLet me know if you know other ways that can make the offline mode experience better. I\'d be happy to add them :) \r\n\r\nI already note the "freeze" modules option, to prevent local modules updates. It would be a cool feature.\r\n\r\n----------\r\n\r\n> @mandubian\'s second bullet point suggests that there\'s a workaround allowing you to use your offline (custom?) dataset with `datasets`. Could you please elaborate on how that should look like?\r\n\r\nIndeed `load_dataset` allows to load remote dataset script (squad, glue, etc.) but also you own local ones.\r\nFor example if you have a dataset script at `./my_dataset/my_dataset.py` then you can do\r\n```python\r\nload_dataset("./my_dataset")\r\n```\r\nand the dataset script will generate your dataset once and for all.\r\n\r\n----------\r\n\r\nAbout I\'m looking into having `csv`, `json`, `text`, `pandas` dataset builders already included in the `datasets` package, so that they are available offline by default, as opposed to the other datasets that require the script to be downloaded.\r\ncf #1724 '],
 'body': ['`datasets.load_dataset("csv", ...)` breaks if you have no connection (There is already this issue https://github.com/huggingface/datasets/issues/761 about it). It seems to be the same for metrics too.\r\n\r\nI create this ticket to discuss a bit and gather what you have in mind or other propositions.\r\n\r\nHere are some points to open discussion:\r\n- if you want to prepare your code/datasets on your machine (having internet connexion) but run it on another offline machine (not having internet connexion), it won\'t work as is, even if you have all files locally on this machine.\r\n- AFAIK, you can make it work if you manually put the python files (csv.py for example) on this offline machine and change your code to `datasets.load_dataset("MY_PATH/csv.py", ...)`. But it would be much better if you could run ths same code without modification if files are available locally.\r\n- I\'ve also been considering the requirement of downloading Python code and execute on your machine to use datasets. This can be an issue in a professional context. Downloading a CSV/H5 file is acceptable, downloading an executable script can open many security issues. We certainly need a mechanism to at least "freeze" the dataset code you retrieved once so that you can review it if you want and then be sure you use this one everywhere and not a version dowloaded from internet.\r\n \r\nWDYT? (thks)\r\n\r\n',
  '`datasets.load_dataset("csv", ...)` breaks if you have no connection (There is already this issue https://github.com/huggingface/datasets/issues/761 about it). It seems to be the same for metrics too.\r\n\r\nI create this ticket to discuss a bit and gather what you have in mind or other propositions.\r\n\r\nHere are some points to open discussion:\r\n- if you want to prepare your code/datasets on your machine (having internet connexion) but run it on another offline machine (not having internet connexion), it won\'t work as is, even if you have all files locally on this machine.\r\n- AFAIK, you can make it work if you manually put the python files (csv.py for example) on this offline machine and change your code to `datasets.load_dataset("MY_PATH/csv.py", ...)`. But it would be much better if you could run ths same code without modification if files are available locally.\r\n- I\'ve also been considering the requirement of downloading Python code and execute on your machine to use datasets. This can be an issue in a professional context. Downloading a CSV/H5 file is acceptable, downloading an executable script can open many security issues. We certainly need a mechanism to at least "freeze" the dataset code you retrieved once so that you can review it if you want and then be sure you use this one everywhere and not a version dowloaded from internet.\r\n \r\nWDYT? (thks)\r\n\r\n',
  '`datasets.load_dataset("csv", ...)` breaks if you have no connection (There is already this issue https://github.com/huggingface/datasets/issues/761 about it). It seems to be the same for metrics too.\r\n\r\nI create this ticket to discuss a bit and gather what you have in mind or other propositions.\r\n\r\nHere are some points to open discussion:\r\n- if you want to prepare your code/datasets on your machine (having internet connexion) but run it on another offline machine (not having internet connexion), it won\'t work as is, even if you have all files locally on this machine.\r\n- AFAIK, you can make it work if you manually put the python files (csv.py for example) on this offline machine and change your code to `datasets.load_dataset("MY_PATH/csv.py", ...)`. But it would be much better if you could run ths same code without modification if files are available locally.\r\n- I\'ve also been considering the requirement of downloading Python code and execute on your machine to use datasets. This can be an issue in a professional context. Downloading a CSV/H5 file is acceptable, downloading an executable script can open many security issues. We certainly need a mechanism to at least "freeze" the dataset code you retrieved once so that you can review it if you want and then be sure you use this one everywhere and not a version dowloaded from internet.\r\n \r\nWDYT? (thks)\r\n\r\n'],
 'comments_length': [47, 76, 179],
 'text': ['Discussion using datasets in offline mode \n`datasets.load_dataset("csv", ...)` breaks if you have no connection (There is already this issue https://github.com/huggingface/datasets/issues/761 about it). It seems to be the same for metrics too.\r\n\r\nI create this ticket to discuss a bit and gather what you have in mind or other propositions.\r\n\r\nHere are some points to open discussion:\r\n- if you want to prepare your code/datasets on your machine (having internet connexion) but run it on another offline machine (not having internet connexion), it won\'t work as is, even if you have all files locally on this machine.\r\n- AFAIK, you can make it work if you manually put the python files (csv.py for example) on this offline machine and change your code to `datasets.load_dataset("MY_PATH/csv.py", ...)`. But it would be much better if you could run ths same code without modification if files are available locally.\r\n- I\'ve also been considering the requirement of downloading Python code and execute on your machine to use datasets. This can be an issue in a professional context. Downloading a CSV/H5 file is acceptable, downloading an executable script can open many security issues. We certainly need a mechanism to at least "freeze" the dataset code you retrieved once so that you can review it if you want and then be sure you use this one everywhere and not a version dowloaded from internet.\r\n \r\nWDYT? (thks)\r\n\r\n \n here is my way to load a dataset offline, but it **requires** an online machine\r\n1. (online machine)\r\n```\r\nimport datasets\r\ndata = datasets.load_dataset(...)\r\ndata.save_to_disk(/YOUR/DATASET/DIR)\r\n```\r\n2. copy the dir from online to the offline machine\r\n3. (offline machine)\r\n```\r\nimport datasets\r\ndata = datasets.load_from_disk(/SAVED/DATA/DIR)\r\n```\r\n\r\nHTH.',
  'Discussion using datasets in offline mode \n`datasets.load_dataset("csv", ...)` breaks if you have no connection (There is already this issue https://github.com/huggingface/datasets/issues/761 about it). It seems to be the same for metrics too.\r\n\r\nI create this ticket to discuss a bit and gather what you have in mind or other propositions.\r\n\r\nHere are some points to open discussion:\r\n- if you want to prepare your code/datasets on your machine (having internet connexion) but run it on another offline machine (not having internet connexion), it won\'t work as is, even if you have all files locally on this machine.\r\n- AFAIK, you can make it work if you manually put the python files (csv.py for example) on this offline machine and change your code to `datasets.load_dataset("MY_PATH/csv.py", ...)`. But it would be much better if you could run ths same code without modification if files are available locally.\r\n- I\'ve also been considering the requirement of downloading Python code and execute on your machine to use datasets. This can be an issue in a professional context. Downloading a CSV/H5 file is acceptable, downloading an executable script can open many security issues. We certainly need a mechanism to at least "freeze" the dataset code you retrieved once so that you can review it if you want and then be sure you use this one everywhere and not a version dowloaded from internet.\r\n \r\nWDYT? (thks)\r\n\r\n \n > here is my way to load a dataset offline, but it **requires** an online machine\n> \n> 1. (online machine)\n> \n> ```\n> \n> import datasets\n> \n> data = datasets.load_dataset(...)\n> \n> data.save_to_disk(/YOUR/DATASET/DIR)\n> \n> ```\n> \n> 2. copy the dir from online to the offline machine\n> \n> 3. (offline machine)\n> \n> ```\n> \n> import datasets\n> \n> data = datasets.load_from_disk(/SAVED/DATA/DIR)\n> \n> ```\n> \n> \n> \n> HTH.\n\n',
  'Discussion using datasets in offline mode \n`datasets.load_dataset("csv", ...)` breaks if you have no connection (There is already this issue https://github.com/huggingface/datasets/issues/761 about it). It seems to be the same for metrics too.\r\n\r\nI create this ticket to discuss a bit and gather what you have in mind or other propositions.\r\n\r\nHere are some points to open discussion:\r\n- if you want to prepare your code/datasets on your machine (having internet connexion) but run it on another offline machine (not having internet connexion), it won\'t work as is, even if you have all files locally on this machine.\r\n- AFAIK, you can make it work if you manually put the python files (csv.py for example) on this offline machine and change your code to `datasets.load_dataset("MY_PATH/csv.py", ...)`. But it would be much better if you could run ths same code without modification if files are available locally.\r\n- I\'ve also been considering the requirement of downloading Python code and execute on your machine to use datasets. This can be an issue in a professional context. Downloading a CSV/H5 file is acceptable, downloading an executable script can open many security issues. We certainly need a mechanism to at least "freeze" the dataset code you retrieved once so that you can review it if you want and then be sure you use this one everywhere and not a version dowloaded from internet.\r\n \r\nWDYT? (thks)\r\n\r\n \n I opened a PR that allows to reload modules that have already been loaded once even if there\'s no internet.\r\n\r\nLet me know if you know other ways that can make the offline mode experience better. I\'d be happy to add them :) \r\n\r\nI already note the "freeze" modules option, to prevent local modules updates. It would be a cool feature.\r\n\r\n----------\r\n\r\n> @mandubian\'s second bullet point suggests that there\'s a workaround allowing you to use your offline (custom?) dataset with `datasets`. Could you please elaborate on how that should look like?\r\n\r\nIndeed `load_dataset` allows to load remote dataset script (squad, glue, etc.) but also you own local ones.\r\nFor example if you have a dataset script at `./my_dataset/my_dataset.py` then you can do\r\n```python\r\nload_dataset("./my_dataset")\r\n```\r\nand the dataset script will generate your dataset once and for all.\r\n\r\n----------\r\n\r\nAbout I\'m looking into having `csv`, `json`, `text`, `pandas` dataset builders already included in the `datasets` package, so that they are available offline by default, as opposed to the other datasets that require the script to be downloaded.\r\ncf #1724 '],
 'embeddings': [[-0.49025774002075195,
   0.2288966178894043,
   -0.03322093188762665,
   0.1388731598854065,
   0.23637259006500244,
   -0.08911502361297607,
   0.5481936931610107,
   0.06737262010574341,
   0.2955964207649231,
   0.24505135416984558,
   -0.010174279101192951,
   -0.06949246674776077,
   0.027625713497400284,
   0.38272812962532043,
   -0.10571826994419098,
   -0.021846435964107513,
   -0.15303930640220642,
   0.0536615327000618,
   -0.1772283911705017,
   0.0896226018667221,
   -0.16522930562496185,
   -0.09213327616453171,
   -0.433723509311676,
   -0.07040667533874512,
   -0.018133023753762245,
   -0.150425523519516,
   -0.08321230858564377,
   0.21943891048431396,
   -0.16612516343593597,
   -0.2807522118091583,
   0.23882056772708893,
   0.1633141040802002,
   0.22919711470603943,
   0.475061297416687,
   -0.00010338118590880185,
   0.02631741762161255,
   0.008209191262722015,
   -0.0013797860592603683,
   -0.2269739955663681,
   -0.4025883078575134,
   -0.21580460667610168,
   -0.5285043716430664,
   0.17964884638786316,
   -0.455070436000824,
   -0.20320361852645874,
   -0.05820460245013237,
   -0.07459710538387299,
   -0.49292701482772827,
   0.3164806365966797,
   0.3498667776584625,
   0.25937753915786743,
   0.5757412910461426,
   -0.13582640886306763,
   -0.27544453740119934,
   -0.16067931056022644,
   -0.15148741006851196,
   -0.14930468797683716,
   0.43661603331565857,
   -0.014577195048332214,
   -0.008213239721953869,
   -0.0025772899389266968,
   0.09523361921310425,
   -0.19615671038627625,
   0.04138578474521637,
   0.3163406550884247,
   0.058681145310401917,
   -0.10160952061414719,
   -0.10181789100170135,
   0.21980217099189758,
   0.39308449625968933,
   0.42616185545921326,
   -0.2737802267074585,
   -0.24700316786766052,
   -0.3390043079853058,
   -0.002341354265809059,
   -0.45674756169319153,
   0.07884830981492996,
   0.18367122113704681,
   0.024228479713201523,
   0.22488391399383545,
   -0.3797210454940796,
   -0.31823933124542236,
   -0.33132433891296387,
   0.16381356120109558,
   -0.32146328687667847,
   0.011169157922267914,
   -0.2536792457103729,
   0.06930145621299744,
   -0.06124458834528923,
   0.09133519232273102,
   -0.17682050168514252,
   -0.28515323996543884,
   0.073911651968956,
   -0.06194626912474632,
   -0.2594500482082367,
   0.02685561031103134,
   0.11837898939847946,
   0.06844884157180786,
   0.1312049925327301,
   0.06520532071590424,
   0.23980149626731873,
   -0.018818117678165436,
   0.07910709083080292,
   0.049734245985746384,
   0.4407643973827362,
   0.2978351414203644,
   0.0075797513127326965,
   -0.1768716275691986,
   0.5290126204490662,
   0.09103387594223022,
   -0.02419465221464634,
   -0.29890763759613037,
   0.25659653544425964,
   -0.30730801820755005,
   0.13212093710899353,
   0.013798408210277557,
   0.36540931463241577,
   -0.3048081398010254,
   -0.1587883085012436,
   -0.013998753391206264,
   0.13926109671592712,
   -0.042462993413209915,
   0.16893219947814941,
   0.25229230523109436,
   -0.2716250717639923,
   0.04514209181070328,
   0.06977436691522598,
   0.39693504571914673,
   -0.29897814989089966,
   -0.26576560735702515,
   -0.058948222547769547,
   -0.12591971457004547,
   -0.11281108856201172,
   0.06377117335796356,
   0.17899096012115479,
   6.031617522239685e-05,
   0.05204311013221741,
   -0.04112791270017624,
   0.24216528236865997,
   -0.07350900769233704,
   0.29814696311950684,
   -0.0951727032661438,
   0.0823780968785286,
   0.23530805110931396,
   0.2750588655471802,
   -0.08741816133260727,
   0.07691602408885956,
   -0.2003217488527298,
   0.037915803492069244,
   0.03879086673259735,
   -0.14262723922729492,
   -0.3582569658756256,
   0.17065684497356415,
   0.27655690908432007,
   -0.6289308667182922,
   -0.17536669969558716,
   -0.32162678241729736,
   0.036760296672582626,
   -0.31611356139183044,
   -0.19427332282066345,
   -0.030853964388370514,
   -0.06167091429233551,
   -0.17800460755825043,
   -0.24536623060703278,
   0.32401105761528015,
   0.5668387413024902,
   -0.3839699327945709,
   0.10502704977989197,
   0.084406279027462,
   -0.16043388843536377,
   -0.17819207906723022,
   0.023398619145154953,
   -0.3148404657840729,
   0.523370087146759,
   -0.013056050054728985,
   -0.3010379672050476,
   0.5681837201118469,
   -0.35509127378463745,
   -0.2651602029800415,
   0.24874603748321533,
   -0.19176092743873596,
   -0.105965755879879,
   -0.10386129468679428,
   0.09011462330818176,
   0.4400767683982849,
   0.07504843920469284,
   -0.08439368009567261,
   0.28901082277297974,
   -0.0351710319519043,
   0.0004676859825849533,
   -0.2186109721660614,
   -0.23697811365127563,
   0.1673177182674408,
   0.2837597131729126,
   0.2555624544620514,
   0.11290067434310913,
   0.30474260449409485,
   -0.19725696742534637,
   0.03916297107934952,
   -0.28212079405784607,
   0.11916562914848328,
   0.16548565030097961,
   0.16971978545188904,
   0.10239702463150024,
   -0.04420816898345947,
   -0.1828148365020752,
   -0.4893229603767395,
   0.2718421518802643,
   0.04788372665643692,
   0.15719571709632874,
   -0.1992018073797226,
   -0.13791599869728088,
   -0.020389126613736153,
   -0.18313105404376984,
   -0.1769694983959198,
   0.027282562106847763,
   0.14106421172618866,
   -0.1107877641916275,
   0.1724623292684555,
   0.12936846911907196,
   -0.25989866256713867,
   0.17829236388206482,
   0.010788077488541603,
   0.002460820134729147,
   -0.13007396459579468,
   0.2903400957584381,
   -0.04923694580793381,
   0.06460003554821014,
   -0.02892918884754181,
   0.08814690262079239,
   0.0581812746822834,
   -0.19372239708900452,
   -0.11858318001031876,
   0.5259695649147034,
   -0.030091093853116035,
   0.06162945553660393,
   0.2687850296497345,
   0.3818563222885132,
   0.3064643442630768,
   -0.012045014649629593,
   0.5338496565818787,
   -0.04272640123963356,
   0.33343762159347534,
   -0.09251046180725098,
   -0.3228541910648346,
   0.7542524337768555,
   -0.15257515013217926,
   0.2171274870634079,
   0.10252596437931061,
   0.018324067816138268,
   0.25997957587242126,
   0.0012790374457836151,
   -0.4040773808956146,
   -0.03595251590013504,
   0.11844836175441742,
   0.002245604991912842,
   0.1811370998620987,
   -0.08507385849952698,
   -0.3064593970775604,
   -0.01529112458229065,
   0.3312464952468872,
   -0.018839720636606216,
   0.17788498103618622,
   -0.06607462465763092,
   -0.030484996736049652,
   0.13060468435287476,
   -0.0831732451915741,
   0.08876849710941315,
   0.5169283151626587,
   0.2506966292858124,
   0.05195707082748413,
   0.22982539236545563,
   -0.031378328800201416,
   -0.256214439868927,
   0.13256661593914032,
   0.2321358621120453,
   0.049241263419389725,
   0.06843416392803192,
   0.10048194974660873,
   -0.023727145045995712,
   -0.20638099312782288,
   -0.052083078771829605,
   -0.054718874394893646,
   0.023271890357136726,
   -0.2868104875087738,

In [289]:
import pandas as pd

samples_df = pd.DataFrame.from_dict(samples.to_dict())
samples_df["scores"] = top_k_scores
samples_df.sort_values("scores", ascending=False, inplace=True)

In [290]:
for _, row in samples_df.iterrows():
    print(f"COMMENT: {row.comments}")
    print(f"SCORE: {row.scores}")
    print(f"TITLE: {row.title}")
    print(f"URL: {row.html_url}")
    print("=" * 50)
    print()

COMMENT: here is my way to load a dataset offline, but it **requires** an online machine
1. (online machine)
```
import datasets
data = datasets.load_dataset(...)
data.save_to_disk(/YOUR/DATASET/DIR)
```
2. copy the dir from online to the offline machine
3. (offline machine)
```
import datasets
data = datasets.load_from_disk(/SAVED/DATA/DIR)
```

HTH.
SCORE: 0.7284623327742736
TITLE: Discussion using datasets in offline mode
URL: https://github.com/huggingface/datasets/issues/824
==================================================

COMMENT: > here is my way to load a dataset offline, but it **requires** an online machine
>
> 1. (online machine)
>
> ```
>
> import datasets
>
> data = datasets.load_dataset(...)
>
> data.save_to_disk(/YOUR/DATASET/DIR)
>
> ```
>
> 2. copy the dir from online to the offline machine
>
> 3. (offline machine)
>
> ```
>
> import datasets
>
> data = datasets.load_from_disk(/SAVED/DATA/DIR)
>
> ```
>
>
>
> HTH.


SCORE: 0.7229038495699982
TITLE: Discussion using datasets in offline mode
URL: https://github.com/huggingface/datasets/issues/824
==================================================

COMMENT: I opened a PR that allows to reload modules that have already been loaded once even if there's no internet.

Let me know if you know other ways that can make the offline mode experience better. I'd be happy to add them :)

I already note the "freeze" modules option, to prevent local modules updates. It would be a cool feature.

----------

> @mandubian's second bullet point suggests that there's a workaround allowing you to use your offline (custom?) dataset with `datasets`. Could you please elaborate on how that should look like?

Indeed `load_dataset` allows to load remote dataset script (squad, glue, etc.) but also you own local ones.
For example if you have a dataset script at `./my_dataset/my_dataset.py` then you can do
```python
load_dataset("./my_dataset")
```
and the dataset script will generate your dataset once and for all.

----------

About I'm looking into having `csv`, `json`, `text`, `pandas` dataset builders already included in the `datasets` package, so that they are available offline by default, as opposed to the other datasets that require the script to be downloaded.
cf #1724
SCORE: 0.7116206133890037
TITLE: Discussion using datasets in offline mode
URL: https://github.com/huggingface/datasets/issues/824
==================================================

COMMENT: The local dataset builders (csv, text , json and pandas) are now part of the `datasets` package since #1726 :)
You can now use them offline
```python
datasets = load_dataset('text', data_files=data_files)
```

We'll do a new release soon
SCORE: 0.6989234127553032
TITLE: Discussion using datasets in offline mode
URL: https://github.com/huggingface/datasets/issues/824
==================================================

COMMENT: Requiring online connection is a deal breaker in some cases unfortunately so it'd be great if offline mode is added similar to how `transformers` loads models offline fine.

@mandubian's second bullet point suggests that there's a workaround allowing you to use your offline (custom?) dataset with `datasets`. Could you please elaborate on how that should look like?
SCORE: 0.6959360555159153
TITLE: Discussion using datasets in offline mode
URL: https://github.com/huggingface/datasets/issues/824
==================================================